-- Idempotent English seed for the existing shared app_content registry.
insert into public.app_content (
  content_key, locale, value, content_group, namespace, description,
  content_version, is_active, platform, sort_order, tags
)
select key, 'en', value, content_group, split_part(key, '.', 1),
       'BEAT shared product copy', 1, true, 'all', ordinal, array['beat', content_group]
from (
  values
  ('welcome.hero.eyebrow','There are many ways to connect','welcome',10),
  ('welcome.hero.title','Find someone on your wavelength.','welcome',20),
  ('welcome.hero.body','Choose what would feel good today. Then meet people nearby who chose the same BEAT and fit what you are looking for.','welcome',30),
  ('welcome.hero.join','Join BEAT','welcome',40),
  ('welcome.hero.sign_in','Already a member? Sign in','welcome',50),
  ('welcome.how_it_works.label','How BEAT works','welcome',60),
  ('welcome.how_it_works.title','Start with the kind of connection you want today.','welcome',70),
  ('welcome.step_1.title','Tell us how you connect','welcome',80),
  ('welcome.step_1.body','Answer ten thoughtful questions so BEAT can understand your natural communication and connection style.','welcome',90),
  ('welcome.step_2.title','Choose today’s BEAT','welcome',100),
  ('welcome.step_2.body','Deep Talk, Coffee, Adventure or Quiet Time: choose what would genuinely feel good today.','welcome',110),
  ('welcome.step_3.title','Meet people who agree','welcome',120),
  ('welcome.step_3.body','Browse everyone nearby who chose the same BEAT and fits your age, gender and distance preferences. Like as many people as you genuinely want to meet.','welcome',130),
  ('welcome.connection.label','Many ways to connect','welcome',140),
  ('welcome.connection.title','Attraction does not follow one script.','welcome',150),
  ('welcome.connection.body_1','Some people connect through conversation. Others through humour, curiosity, music, movement, silence or a shared adventure.','welcome',160),
  ('welcome.connection.body_2','BEAT helps you find people who want a similar kind of connection today, while still leaving you free to browse, choose and follow your own curiosity.','welcome',170),
  ('welcome.connection.feature.shared_intention','Shared intention','welcome',180),
  ('welcome.connection.feature.compatibility','Personal compatibility','welcome',190),
  ('welcome.connection.feature.verified','Verified profiles','welcome',200),
  ('welcome.connection.feature.own_pace','Your own pace','welcome',210),
  ('welcome.cta.title','What would feel good today?','welcome',220),
  ('welcome.cta.body','Choose your BEAT and discover who is on the same wavelength.','welcome',230),
  ('welcome.cta.button','Join BEAT','welcome',240),
  ('auth.sign_up.title','Join BEAT','auth',250),
  ('auth.sign_up.body','Create your profile, discover how you connect and choose what would feel good today.','auth',260),
  ('auth.sign_in.title','Welcome back','auth',270),
  ('auth.sign_in.body','Your next connection may already be on your wavelength.','auth',280),
  ('onboarding.intro.eyebrow','Your connection profile','onboarding',290),
  ('onboarding.intro.title','How do you naturally connect?','onboarding',300),
  ('onboarding.intro.body','Ten quick questions help BEAT understand your communication style and show you more relevant people first. There are no right answers and no boxes you need to fit into.','onboarding',310),
  ('onboarding.progress','Question {current} of 10','onboarding',320),
  ('onboarding.back','Back','onboarding',330),
  ('onboarding.next','Next','onboarding',340),
  ('onboarding.finish','See my profile','onboarding',350),
  ('onboarding.result.eyebrow','Your connection profile','onboarding',360),
  ('onboarding.result.title','This is how you tend to connect.','onboarding',370),
  ('onboarding.result.disclaimer','This profile helps BEAT rank compatible people. It does not decide who you can meet.','onboarding',380),
  ('onboarding.result.action','Choose today’s BEAT','onboarding',390),
  ('profile.connection.title','How I connect','profile',400),
  ('profile.connection.body','Your connection profile helps BEAT understand which people may feel more natural to meet.','profile',410),
  ('profile.connection.label','My connection profile','profile',420),
  ('profile.connection.version','Profile created from BEAT Interview {version}','profile',430),
  ('profile.connection.retake','Retake interview','profile',440),
  ('profile.connection.retake_confirm.title','Retake the interview?','profile',450),
  ('profile.connection.retake_confirm.body','Your new answers will replace your current connection profile and update future compatibility rankings.','profile',460),
  ('profile.connection.retake_confirm.cancel','Keep current profile','profile',470),
  ('profile.connection.retake_confirm.confirm','Retake interview','profile',480),
  ('wheel.question','What would feel good today?','wheel',490),
  ('wheel.instruction','Spin, scroll or use the arrows to explore.','wheel',500),
  ('wheel.selected_prefix','Today I’d love to…','wheel',510),
  ('wheel.random','Surprise me','wheel',520),
  ('wheel.confirm','Choose this BEAT','wheel',530),
  ('settings.discovery.title','Discovery preferences','settings',540),
  ('settings.discovery.body','These preferences determine who can appear when you choose a BEAT.','settings',550),
  ('settings.beat_wheel.title','Your BEAT wheel','settings',560),
  ('settings.beat_wheel.body','Choose which experiences can appear on your wheel. Keep at least one active.','settings',570),
  ('settings.beat_wheel.included','Included','settings',580),
  ('settings.beat_wheel.hidden','Hidden','settings',590),
  ('settings.save','Save preferences','settings',600),
  ('settings.saved','Preferences saved','settings',610),
  ('discovery.no_beat.title','What would feel good today?','discovery',620),
  ('discovery.no_beat.body','Choose a BEAT to meet people nearby who want the same kind of connection.','discovery',630),
  ('discovery.active.label','Today’s BEAT','discovery',640),
  ('discovery.active.change','Change','discovery',650),
  ('discovery.people.title','People open to {selectedBeat} today','discovery',660),
  ('discovery.people.body','They also fit your current age, gender and distance preferences.','discovery',670),
  ('discovery.loading','Finding people on your wavelength…','discovery',680),
  ('discovery.empty.title','No one nearby has chosen this BEAT yet.','discovery',690),
  ('discovery.empty.body','Try another BEAT, adjust your discovery preferences or check again later.','discovery',700),
  ('discovery.empty.change_beat','Choose another BEAT','discovery',710),
  ('discovery.empty.preferences','Adjust discovery preferences','discovery',720),
  ('discovery.reviewed.title','You have seen everyone here for now.','discovery',730),
  ('discovery.reviewed.body','Check back later or choose another BEAT to meet a different pool.','discovery',740),
  ('discovery.reviewed.change_beat','Choose another BEAT','discovery',750),
  ('discovery.like','Like','discovery',760),
  ('discovery.pass','Pass','discovery',770),
  ('match.title','You found the same BEAT.','match',780),
  ('match.body','You both chose each other. Start wherever feels natural.','match',790),
  ('match.message','Send a message','match',800),
  ('match.keep_browsing','Keep browsing','match',810)
) as seed(key, value, content_group, ordinal)
on conflict do nothing;

insert into public.app_content (
  content_key, locale, value, content_group, namespace, description,
  content_version, is_active, platform, sort_order, tags
)
select
  'wheel.option.' || beat || '.' || field, 'en', value, 'wheel', 'wheel',
  'Stable daily BEAT option copy', 1, true, 'all', 1000 + ordinal,
  array['beat', 'wheel', beat]
from (
  values
  ('deep_talk','label','Deep Talk',1),('deep_talk','answer','Have a deep conversation',2),('deep_talk','description','One of those conversations where we forget to check our phones.',3),
  ('coffee','label','Coffee',4),('coffee','answer','Meet for a casual coffee',5),('coffee','description','No pressure. No performance. Just see how it feels.',6),
  ('dreamy_walk','label','Dreamy Walk',7),('dreamy_walk','answer','Take a dreamy walk',8),('dreamy_walk','description','Walk side by side and let the conversation find its own direction.',9),
  ('quiet_time','label','Quiet Time',10),('quiet_time','answer','Spend quiet time together',11),('quiet_time','description','Comfortable company without needing to fill every silence.',12),
  ('laugh','label','Laugh',13),('laugh','answer','Laugh out loud',14),('laugh','description','Keep it light, playful and wonderfully unserious.',15),
  ('flirt','label','Flirt',16),('flirt','answer','Flirt respectfully',17),('flirt','description','A little chemistry, clear signals and good boundaries.',18),
  ('adventure','label','Adventure',19),('adventure','answer','Have an adventurous day',20),('adventure','description','Leave the routine behind and see where the day takes us.',21),
  ('create','label','Create',22),('create','answer','Create something meaningful',23),('create','description','Cook, draw, build, write or make something together.',24),
  ('museum','label','Museum',25),('museum','answer','Visit a museum or gallery',26),('museum','description','Discover something beautiful and have someone to talk about it with.',27),
  ('playlist','label','Playlist',28),('playlist','answer','Share our playlists',29),('playlist','description','Trade the songs that say more about us than a profile ever could.',30),
  ('philosophy','label','Philosophy',31),('philosophy','answer','Get lost in philosophy',32),('philosophy','description','Big questions, curious minds and no urgent need for final answers.',33),
  ('outside','label','Outside',34),('outside','answer','Get outside',35),('outside','description','Fresh air, open space and somewhere better than another screen.',36),
  ('unforgettable','label','Unforgettable',37),('unforgettable','answer','Do something unforgettable',38),('unforgettable','description','Create the kind of story we will still enjoy telling later.',39)
) as options(beat, field, value, ordinal)
on conflict do nothing;
